apiVersion: v1
kind: Service
metadata:
  name: harness-service
spec:
  selector:
    app: harness-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
